name: Python CI

on:
  pull_request_target:
    branches:
      - '**'

jobs:
  run-ci:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        # TODO: add windows matrix
        os: [macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Run tests using the shell script (macOS compatible).
        if: matrix.os == 'macos-latest'
        run: |
          sh install/install_openadapt.sh
          SKIP_POETRY_SHELL=1
          REPO="${{ github.event.pull_request.head.repo.full_name }}"  # Using full_name for repository
          BRANCH="${{ github.event.pull_request.head.ref }}"  # Using ref for branch
